### ISSUE TITLE
🗄️ Development 📌

### ISSUE THREAD

**Issue by EnzoHB** [EnzoHB/Math-Related-Algorithms#1]
# ToDo List
**A Few algorithms I plan to add in the future :**

- [ ] **Equations Solver**

  - [ ] **First Degree Equations;**
  - [ ] **Second Degree Equations;**
  - [ ] **Third Degree Equations;**
  - [ ] **So on...**

- [ ] **Systems Solver**

  - [ ] **By Substitution;**
  - [ ] **By Elimination;**
  - [ ] **By Augmented Matrices;**

- [ ] **Mathematical Rule**
  - [ ] **Rule Of Three;**
  - [ ] **Compound rule of Three;**
  - [ ] **So on..**

- [ ] **Formulas**
  - [ ]  **Bhaskara I's Sine Approximation Formula;**
  - [ ]  **Pythagorean Theorem;**
  - [ ]  **So on..**
 
- [ ] **Others - As I Learn Something Interesting at School;**
  - [ ] **Undefined;**
  - [ ] **Undefined;**
  - [ ] **Undefined;**
